[workspace]

resolver = "2"

members = [
    "crdt-enc",
    "crdt-enc-gpgme",
    "crdt-enc-xchacha20poly1305",
    "crdt-enc-tokio",
    "examples/*",
]

[patch.crates-io]
agnostik = {git = "https://github.com/chpio/agnostik.git", branch = "master"}
